# Generated by Django 5.0.1 on 2024-01-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='comment',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
