# Generated by Django 5.0.1 on 2024-02-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='comment',
        ),
    ]
