# Generated by Django 5.0.1 on 2024-02-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_text_comment_comment_alter_comment_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='comments',
            field=models.ManyToManyField(related_name='cards', to='api.comment'),
        ),
    ]
