# Generated by Django 5.0.1 on 2024-02-02 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cards_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='comments',
        ),
        migrations.AddField(
            model_name='cards',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment'),
        ),
    ]
