# Generated by Django 5.0.1 on 2024-02-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_cards_comments_cards_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='card',
            new_name='comments',
        ),
    ]
