# Generated by Django 5.0.1 on 2024-02-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_card_cards_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='comments',
        ),
    ]
